CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE donation_packages (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        title character varying(200) NOT NULL,
        description character varying(1000) NOT NULL,
        suggested_amounts character varying(500),
        is_active boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_donation_packages PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE nav_sections (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        icon character varying(50),
        "order" integer NOT NULL,
        is_published boolean NOT NULL,
        type integer NOT NULL,
        url character varying(500),
        is_external boolean NOT NULL,
        open_in_new_tab boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_nav_sections PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE servers (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        ip_address text NOT NULL,
        port integer NOT NULL,
        rcon_password character varying(100),
        map_name text NOT NULL,
        current_players integer NOT NULL,
        max_players integer NOT NULL,
        is_online boolean NOT NULL,
        last_checked timestamp without time zone NOT NULL,
        CONSTRAINT p_k_servers PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE site_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        key text NOT NULL,
        value text NOT NULL,
        category text NOT NULL,
        description text NOT NULL,
        data_type text NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_site_settings PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE slider_images (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        image_url text NOT NULL,
        title character varying(100) NOT NULL,
        description character varying(500) NOT NULL,
        "order" integer NOT NULL,
        buttons text,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_slider_images PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE smtp_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        host character varying(255) NOT NULL,
        port integer NOT NULL,
        username character varying(255) NOT NULL,
        password character varying(500) NOT NULL,
        enable_ssl boolean NOT NULL,
        from_email character varying(255) NOT NULL,
        from_name character varying(255) NOT NULL,
        is_configured boolean NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_smtp_settings PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        username character varying(50) NOT NULL,
        email text NOT NULL,
        password_hash text NOT NULL,
        avatar_url text,
        steam_id character varying(50),
        steam_profile_url text,
        last_ip text,
        is_admin boolean NOT NULL,
        is_blocked boolean NOT NULL,
        blocked_at timestamp without time zone,
        block_reason text,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_users PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE yoomoney_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        wallet_number character varying(100) NOT NULL,
        secret_key character varying(500) NOT NULL,
        is_configured boolean NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_yoomoney_settings PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE admin_tariff_groups (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        server_id integer NOT NULL,
        name character varying(100) NOT NULL,
        description character varying(1000) NOT NULL,
        "order" integer NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_admin_tariff_groups PRIMARY KEY (id),
        CONSTRAINT f_k_admin_tariff_groups__servers_server_id FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE sourcebans_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        server_id integer NOT NULL,
        host character varying(255) NOT NULL,
        port integer NOT NULL,
        database character varying(100) NOT NULL,
        username character varying(100) NOT NULL,
        password character varying(500) NOT NULL,
        is_configured boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_sourcebans_settings PRIMARY KEY (id),
        CONSTRAINT f_k_sourcebans_settings_servers_server_id FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE vip_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        server_id integer NOT NULL,
        host character varying(255) NOT NULL,
        port integer NOT NULL,
        database character varying(100) NOT NULL,
        username character varying(100) NOT NULL,
        password character varying(500) NOT NULL,
        is_configured boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_vip_settings PRIMARY KEY (id),
        CONSTRAINT f_k_vip_settings_servers_server_id FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE vip_tariffs (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        server_id integer NOT NULL,
        name character varying(100) NOT NULL,
        description character varying(1000) NOT NULL,
        group_name character varying(64) NOT NULL,
        is_active boolean NOT NULL,
        "order" integer NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_vip_tariffs PRIMARY KEY (id),
        CONSTRAINT f_k_vip_tariffs_servers_server_id FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE blocked_ips (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        ip_address character varying(45) NOT NULL,
        reason text,
        blocked_at timestamp without time zone NOT NULL,
        blocked_by_user_id integer,
        CONSTRAINT p_k_blocked_ips PRIMARY KEY (id),
        CONSTRAINT f_k_blocked_ips__users_blocked_by_user_id FOREIGN KEY (blocked_by_user_id) REFERENCES users (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE custom_pages (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        title character varying(200) NOT NULL,
        content text NOT NULL,
        summary character varying(500),
        slug character varying(200) NOT NULL,
        cover_image text,
        author_id integer NOT NULL,
        is_published boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        view_count integer NOT NULL,
        CONSTRAINT p_k_custom_pages PRIMARY KEY (id),
        CONSTRAINT f_k_custom_pages__users_author_id FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE events (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        title character varying(200) NOT NULL,
        content text NOT NULL,
        summary character varying(500),
        slug character varying(200) NOT NULL,
        cover_image text,
        author_id integer NOT NULL,
        is_published boolean NOT NULL,
        start_date timestamp without time zone NOT NULL,
        end_date timestamp without time zone NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        view_count integer NOT NULL,
        like_count integer NOT NULL,
        comment_count integer NOT NULL,
        is_start_notification_sent boolean NOT NULL,
        is_end_notification_sent boolean NOT NULL,
        is_created_notification_sent boolean NOT NULL,
        CONSTRAINT p_k_events PRIMARY KEY (id),
        CONSTRAINT f_k_events__users_author_id FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE news (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        title character varying(200) NOT NULL,
        content text NOT NULL,
        summary character varying(500),
        slug character varying(200) NOT NULL,
        cover_image text,
        author_id integer NOT NULL,
        is_published boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        view_count integer NOT NULL,
        like_count integer NOT NULL,
        comment_count integer NOT NULL,
        CONSTRAINT p_k_news PRIMARY KEY (id),
        CONSTRAINT f_k_news__users_author_id FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE notifications (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        title character varying(200) NOT NULL,
        message character varying(1000) NOT NULL,
        type character varying(50) NOT NULL,
        is_read boolean NOT NULL,
        related_entity_id integer,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_notifications PRIMARY KEY (id),
        CONSTRAINT f_k_notifications__users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE password_reset_tokens (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        token character varying(500) NOT NULL,
        user_id integer NOT NULL,
        expires_at timestamp without time zone NOT NULL,
        is_used boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        used_at timestamp without time zone,
        CONSTRAINT p_k_password_reset_tokens PRIMARY KEY (id),
        CONSTRAINT f_k_password_reset_tokens__users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE telegram_subscribers (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        chat_id bigint NOT NULL,
        user_id integer,
        username text,
        first_name text,
        last_name text,
        is_active boolean NOT NULL,
        subscribed_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_telegram_subscribers PRIMARY KEY (id),
        CONSTRAINT f_k_telegram_subscribers__users_user_id FOREIGN KEY (user_id) REFERENCES users (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE vip_applications (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        username character varying(150) NOT NULL,
        steam_id character varying(50) NOT NULL,
        server_id integer NOT NULL,
        hours_per_week integer,
        reason text NOT NULL,
        status character varying(20) NOT NULL,
        admin_id integer,
        admin_comment text,
        vip_group character varying(128),
        duration_days integer,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        processed_at timestamp without time zone,
        CONSTRAINT p_k_vip_applications PRIMARY KEY (id),
        CONSTRAINT f_k_vip_applications_servers_server_id FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE,
        CONSTRAINT f_k_vip_applications_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE admin_tariffs (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        server_id integer NOT NULL,
        name character varying(100) NOT NULL,
        description character varying(1000) NOT NULL,
        flags character varying(100),
        group_name character varying(100),
        immunity integer NOT NULL,
        is_active boolean NOT NULL,
        "order" integer NOT NULL,
        created_at timestamp without time zone NOT NULL,
        admin_tariff_group_id integer,
        CONSTRAINT p_k_admin_tariffs PRIMARY KEY (id),
        CONSTRAINT f_k_admin_tariffs__servers_server_id FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE,
        CONSTRAINT f_k_admin_tariffs_admin_tariff_groups_admin_tariff_group_id FOREIGN KEY (admin_tariff_group_id) REFERENCES admin_tariff_groups (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE vip_tariff_options (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tariff_id integer NOT NULL,
        duration_days integer NOT NULL,
        price numeric(10,2) NOT NULL,
        "order" integer NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_vip_tariff_options PRIMARY KEY (id),
        CONSTRAINT f_k_vip_tariff_options_vip_tariffs_tariff_id FOREIGN KEY (tariff_id) REFERENCES vip_tariffs (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE custom_page_media (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        custom_page_id integer NOT NULL,
        media_url text NOT NULL,
        media_type character varying(20) NOT NULL,
        "order" integer NOT NULL,
        CONSTRAINT p_k_custom_page_media PRIMARY KEY (id),
        CONSTRAINT f_k_custom_page_media_custom_pages_custom_page_id FOREIGN KEY (custom_page_id) REFERENCES custom_pages (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE custom_page_views (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        custom_page_id integer NOT NULL,
        user_id integer,
        ip_address character varying(45),
        view_date timestamp without time zone NOT NULL,
        CONSTRAINT p_k_custom_page_views PRIMARY KEY (id),
        CONSTRAINT f_k_custom_page_views__users_user_id FOREIGN KEY (user_id) REFERENCES users (id),
        CONSTRAINT f_k_custom_page_views_custom_pages_custom_page_id FOREIGN KEY (custom_page_id) REFERENCES custom_pages (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE nav_section_items (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        section_id integer NOT NULL,
        name character varying(100) NOT NULL,
        icon character varying(50),
        "order" integer NOT NULL,
        is_published boolean NOT NULL,
        type integer NOT NULL,
        url character varying(500),
        custom_page_id integer,
        open_in_new_tab boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_nav_section_items PRIMARY KEY (id),
        CONSTRAINT f_k_nav_section_items_custom_pages_custom_page_id FOREIGN KEY (custom_page_id) REFERENCES custom_pages (id) ON DELETE SET NULL,
        CONSTRAINT f_k_nav_section_items_nav_sections_section_id FOREIGN KEY (section_id) REFERENCES nav_sections (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE event_comments (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        event_id integer NOT NULL,
        user_id integer NOT NULL,
        content character varying(2000) NOT NULL,
        parent_comment_id integer,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_event_comments PRIMARY KEY (id),
        CONSTRAINT f_k_event_comments__users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
        CONSTRAINT f_k_event_comments_event_comments_parent_comment_id FOREIGN KEY (parent_comment_id) REFERENCES event_comments (id) ON DELETE RESTRICT,
        CONSTRAINT f_k_event_comments_events_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE event_likes (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        event_id integer NOT NULL,
        user_id integer NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_event_likes PRIMARY KEY (id),
        CONSTRAINT f_k_event_likes__users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
        CONSTRAINT f_k_event_likes_events_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE event_media (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        event_id integer NOT NULL,
        media_url text NOT NULL,
        media_type character varying(20) NOT NULL,
        "order" integer NOT NULL,
        CONSTRAINT p_k_event_media PRIMARY KEY (id),
        CONSTRAINT f_k_event_media_events_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE event_views (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        event_id integer NOT NULL,
        user_id integer,
        ip_address character varying(45),
        view_date timestamp without time zone NOT NULL,
        CONSTRAINT p_k_event_views PRIMARY KEY (id),
        CONSTRAINT f_k_event_views__users_user_id FOREIGN KEY (user_id) REFERENCES users (id),
        CONSTRAINT f_k_event_views_events_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE news_comments (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        news_id integer NOT NULL,
        user_id integer NOT NULL,
        content character varying(2000) NOT NULL,
        parent_comment_id integer,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_news_comments PRIMARY KEY (id),
        CONSTRAINT f_k_news_comments__users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
        CONSTRAINT f_k_news_comments_news_comments_parent_comment_id FOREIGN KEY (parent_comment_id) REFERENCES news_comments (id) ON DELETE RESTRICT,
        CONSTRAINT f_k_news_comments_news_news_id FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE news_likes (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        news_id integer NOT NULL,
        user_id integer NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_news_likes PRIMARY KEY (id),
        CONSTRAINT f_k_news_likes__users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
        CONSTRAINT f_k_news_likes_news_news_id FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE news_media (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        news_id integer NOT NULL,
        media_url text NOT NULL,
        media_type character varying(20) NOT NULL,
        "order" integer NOT NULL,
        CONSTRAINT p_k_news_media PRIMARY KEY (id),
        CONSTRAINT f_k_news_media_news_news_id FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE news_views (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        news_id integer NOT NULL,
        user_id integer,
        ip_address character varying(45),
        view_date timestamp without time zone NOT NULL,
        CONSTRAINT p_k_news_views PRIMARY KEY (id),
        CONSTRAINT f_k_news_views__users_user_id FOREIGN KEY (user_id) REFERENCES users (id),
        CONSTRAINT f_k_news_views_news_news_id FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE admin_tariff_options (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tariff_id integer NOT NULL,
        duration_days integer NOT NULL,
        price numeric(10,2) NOT NULL,
        "order" integer NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        requires_password boolean NOT NULL,
        CONSTRAINT p_k_admin_tariff_options PRIMARY KEY (id),
        CONSTRAINT f_k_admin_tariff_options_admin_tariffs_tariff_id FOREIGN KEY (tariff_id) REFERENCES admin_tariffs (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE user_admin_privileges (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        steam_id character varying(50) NOT NULL,
        server_id integer NOT NULL,
        tariff_id integer,
        tariff_option_id integer,
        flags character varying(100),
        group_name character varying(100),
        immunity integer NOT NULL,
        starts_at timestamp without time zone NOT NULL,
        expires_at timestamp without time zone NOT NULL,
        is_active boolean NOT NULL,
        sourcebans_admin_id integer,
        transaction_id integer,
        admin_password character varying(100),
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_user_admin_privileges PRIMARY KEY (id),
        CONSTRAINT f_k_user_admin_privileges_admin_tariff_options_tariff_option_id FOREIGN KEY (tariff_option_id) REFERENCES admin_tariff_options (id),
        CONSTRAINT f_k_user_admin_privileges_admin_tariffs_tariff_id FOREIGN KEY (tariff_id) REFERENCES admin_tariffs (id),
        CONSTRAINT f_k_user_admin_privileges_servers_server_id FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE,
        CONSTRAINT f_k_user_admin_privileges_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE donation_transactions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        transaction_id character varying(255) NOT NULL,
        user_id integer,
        steam_id character varying(50),
        amount numeric(10,2) NOT NULL,
        type character varying(20) NOT NULL,
        tariff_id integer,
        tariff_option_id integer,
        vip_tariff_id integer,
        vip_tariff_option_id integer,
        privilege_id integer,
        server_id integer,
        admin_password character varying(100),
        status character varying(20) NOT NULL,
        payment_url character varying(1000),
        pending_expires_at timestamp without time zone,
        payment_method character varying(50),
        label character varying(255),
        expires_at timestamp without time zone,
        created_at timestamp without time zone NOT NULL,
        completed_at timestamp without time zone,
        cancelled_at timestamp without time zone,
        CONSTRAINT p_k_donation_transactions PRIMARY KEY (id),
        CONSTRAINT f_k_donation_transactions__servers_server_id FOREIGN KEY (server_id) REFERENCES servers (id),
        CONSTRAINT f_k_donation_transactions__users_user_id FOREIGN KEY (user_id) REFERENCES users (id),
        CONSTRAINT f_k_donation_transactions_admin_tariff_options_tariff_option_id FOREIGN KEY (tariff_option_id) REFERENCES admin_tariff_options (id),
        CONSTRAINT f_k_donation_transactions_admin_tariffs_tariff_id FOREIGN KEY (tariff_id) REFERENCES admin_tariffs (id),
        CONSTRAINT f_k_donation_transactions_user_admin_privileges_privilege_id FOREIGN KEY (privilege_id) REFERENCES user_admin_privileges (id),
        CONSTRAINT "f_k_donation_transactions_vip_tariff_options_vip_tariff_option_~" FOREIGN KEY (vip_tariff_option_id) REFERENCES vip_tariff_options (id),
        CONSTRAINT f_k_donation_transactions_vip_tariffs_vip_tariff_id FOREIGN KEY (vip_tariff_id) REFERENCES vip_tariffs (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE TABLE user_vip_privileges (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        steam_id character varying(50) NOT NULL,
        server_id integer NOT NULL,
        tariff_id integer,
        tariff_option_id integer,
        group_name character varying(64) NOT NULL,
        starts_at timestamp without time zone NOT NULL,
        expires_at timestamp without time zone NOT NULL,
        is_active boolean NOT NULL,
        transaction_id integer,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT p_k_user_vip_privileges PRIMARY KEY (id),
        CONSTRAINT f_k_user_vip_privileges_donation_transactions_transaction_id FOREIGN KEY (transaction_id) REFERENCES donation_transactions (id),
        CONSTRAINT f_k_user_vip_privileges_servers_server_id FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE,
        CONSTRAINT f_k_user_vip_privileges_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
        CONSTRAINT f_k_user_vip_privileges_vip_tariff_options_tariff_option_id FOREIGN KEY (tariff_option_id) REFERENCES vip_tariff_options (id),
        CONSTRAINT f_k_user_vip_privileges_vip_tariffs_tariff_id FOREIGN KEY (tariff_id) REFERENCES vip_tariffs (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_admin_tariff_groups_server_id_is_active" ON admin_tariff_groups (server_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_admin_tariff_options_tariff_id_is_active" ON admin_tariff_options (tariff_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_admin_tariffs_admin_tariff_group_id ON admin_tariffs (admin_tariff_group_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_admin_tariffs_server_id_is_active" ON admin_tariffs (server_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_blocked_ips_blocked_by_user_id ON blocked_ips (blocked_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_blocked_ips_ip_address" ON blocked_ips (ip_address);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_custom_page_media_custom_page_id ON custom_page_media (custom_page_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_custom_page_views_user_id ON custom_page_views (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_custom_page_views_custom_page_id_ip_address_view_date" ON custom_page_views (custom_page_id, ip_address, view_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_custom_page_views_custom_page_id_user_id_view_date" ON custom_page_views (custom_page_id, user_id, view_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_custom_pages_author_id ON custom_pages (author_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_custom_pages_slug" ON custom_pages (slug);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX i_x_donation_transactions_privilege_id ON donation_transactions (privilege_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_donation_transactions_server_id ON donation_transactions (server_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_donation_transactions_tariff_id ON donation_transactions (tariff_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_donation_transactions_tariff_option_id ON donation_transactions (tariff_option_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_donation_transactions_vip_tariff_id ON donation_transactions (vip_tariff_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_donation_transactions_vip_tariff_option_id ON donation_transactions (vip_tariff_option_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_donation_transactions_steam_id" ON donation_transactions (steam_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_donation_transactions_transaction_id" ON donation_transactions (transaction_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_donation_transactions_user_id_status" ON donation_transactions (user_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_event_comments_event_id ON event_comments (event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_event_comments_parent_comment_id ON event_comments (parent_comment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_event_comments_user_id ON event_comments (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_event_likes_user_id ON event_likes (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_event_likes_event_id_user_id" ON event_likes (event_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_event_media_event_id ON event_media (event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_event_views_user_id ON event_views (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_event_views_event_id_ip_address_view_date" ON event_views (event_id, ip_address, view_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_event_views_event_id_user_id_view_date" ON event_views (event_id, user_id, view_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_events_author_id ON events (author_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_events_slug" ON events (slug);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_nav_section_items_custom_page_id ON nav_section_items (custom_page_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_nav_section_items_section_id_order" ON nav_section_items (section_id, "order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_nav_sections_is_published" ON nav_sections (is_published);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_nav_sections_order" ON nav_sections ("order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_news_author_id ON news (author_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_news_slug" ON news (slug);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_news_comments_news_id ON news_comments (news_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_news_comments_parent_comment_id ON news_comments (parent_comment_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_news_comments_user_id ON news_comments (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_news_likes_user_id ON news_likes (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_news_likes_news_id_user_id" ON news_likes (news_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_news_media_news_id ON news_media (news_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_news_views_user_id ON news_views (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_news_views_news_id_ip_address_view_date" ON news_views (news_id, ip_address, view_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_news_views_news_id_user_id_view_date" ON news_views (news_id, user_id, view_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_notifications_created_at" ON notifications (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_notifications_user_id_is_read" ON notifications (user_id, is_read);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_password_reset_tokens_token" ON password_reset_tokens (token);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_password_reset_tokens_user_id_is_used" ON password_reset_tokens (user_id, is_used);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_site_settings_category" ON site_settings (category);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_site_settings_key" ON site_settings (key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_sourcebans_settings_server_id ON sourcebans_settings (server_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_telegram_subscribers_user_id ON telegram_subscribers (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_telegram_subscribers_chat_id" ON telegram_subscribers (chat_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_user_admin_privileges_server_id ON user_admin_privileges (server_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_user_admin_privileges_tariff_id ON user_admin_privileges (tariff_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_user_admin_privileges_tariff_option_id ON user_admin_privileges (tariff_option_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_user_admin_privileges_expires_at" ON user_admin_privileges (expires_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_user_admin_privileges_steam_id_server_id_is_active" ON user_admin_privileges (steam_id, server_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_user_admin_privileges_user_id_server_id_is_active" ON user_admin_privileges (user_id, server_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_user_vip_privileges_server_id ON user_vip_privileges (server_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_user_vip_privileges_tariff_id ON user_vip_privileges (tariff_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_user_vip_privileges_tariff_option_id ON user_vip_privileges (tariff_option_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_user_vip_privileges_transaction_id ON user_vip_privileges (transaction_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_user_vip_privileges_expires_at" ON user_vip_privileges (expires_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_user_vip_privileges_steam_id_server_id_is_active" ON user_vip_privileges (steam_id, server_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_user_vip_privileges_user_id_server_id_is_active" ON user_vip_privileges (user_id, server_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_users_username" ON users (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_vip_applications_server_id ON vip_applications (server_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_vip_applications_user_id_server_id_status" ON vip_applications (user_id, server_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX i_x_vip_settings_server_id ON vip_settings (server_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_vip_tariff_options_tariff_id_is_active" ON vip_tariff_options (tariff_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    CREATE INDEX "IX_vip_tariffs_server_id_is_active" ON vip_tariffs (server_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227234636_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251227234636_InitialCreate', '9.0.0');
    END IF;
END $EF$;
COMMIT;

